### ISSUE TITLE
Issue when building the project

### ISSUE THREAD

**Issue by mudassir-mukhtar-ahmed** [creativetimofficial/paper-kit-2-angular#18]
Hello, Unable to build the project. Getting multiple errors. 

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: paper-kit-2-angular@1.4.0
npm ERR! Found: zone.js@0.11.3
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"0.11.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@11.0.4
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"11.0.4" from the root project
npm ERR!   peer @angular/core@"11.0.4" from @angular/animations@11.0.4
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"11.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/mahmed5/.npm/eresolve-report.txt for a full report.

**Comment by bartengine27** [comment]
in package.json change the ng-bootstrap/ng-bootstrap dependency to 
`"@ng-bootstrap/ng-bootstrap": "13.0.0",`
for Angular 14.2.0
