### ISSUE TITLE
navbar collapse menu doesn't work if i import paper-kit.scss on component

### ISSUE THREAD

**Issue by MihaiHoriaPopescu** [creativetimofficial/paper-kit-2-angular#3]
Hello, i have some problems with my navbar menu, since i don't use the paper-kit.scss style for all my web portal i import it only for the components i use it (for example: navbar, landing). The style on the page works fine, but the toggle menu doesn't open (on the small pages) when the menu is collapsed. I tried to import it as global and works. So when i press the button of the menu collapsed the menu didn't open. I verify that the style class is added on the elements.

**Comment by chelaruc** [comment]
@Pescu when you import all the scss into a component, it will only take the scss for the classes in that component. You need to import paper-kit.scss as global.

**Comment by MihaiHoriaPopescu** [comment]
@chelaruc ok, thank you for the response.
