### ISSUE TITLE
not shown hamburger menu

### ISSUE THREAD

**Issue by SadovovAlex** [creativetimofficial/paper-kit-2-angular#6]
<button class="navbar-toggler navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" 
             aria-label="Toggle navigation" (click)="sidebarToggle()">
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
            </button>

not show in the browser

**Comment by chelaruc** [comment]
@SadovovAlex can you give me more details about that? Like OS and browser. The burger menu appears only on mobile screen
![screen shot 2018-06-22 at 11 59 57](https://user-images.githubusercontent.com/22840626/41768074-f23c01fc-7613-11e8-9f22-2bd3fce7db5d.png)

**Comment by SadovovAlex** [comment]
I understand =) only mobile screen, not shown on my fullHD. Thx
